/*
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package leapclient

type RequestResetPassword struct {
	Username string `json:"username"`
	PasswordResetToken string `json:"passwordResetToken"`
	NewPassword string `json:"newPassword"`
}
