/*
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package leapclient

type RequestStationSettings struct {
	DisplayName string `json:"displayName"`
	Mode string `json:"mode"`
	QrCode string `json:"qrCode,omitempty"`
}
