/*
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package leapclient

import (
	"time"
)

type Session struct {
	SessionId string `json:"sessionId,omitempty"`
	Reference string `json:"reference,omitempty"`
	State string `json:"state,omitempty"`
	StartedOnUtc time.Time `json:"startedOnUtc,omitempty"`
	StartDuration string `json:"startDuration,omitempty"`
	MaxDurationLimit string `json:"maxDurationLimit,omitempty"`
}
