/*
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package leapclient

type CreatedSession struct {
	StationId string `json:"stationId,omitempty"`
	SessionId string `json:"sessionId,omitempty"`
}
