/*
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package leapclient

type RequestRegisterUser struct {
	Username string `json:"username"`
	EMailAddress string `json:"eMailAddress"`
	Password string `json:"password"`
}
